### ISSUE TITLE
Using CefSharp in class library

### ISSUE THREAD

**Issue by softboy99** [cefsharp/Questions-and-Support#1]
a winform class libray allow form in it? i found CefSharp.winform lib cannot run in in winform Class Library? which are correct in .exe. I have a exe (only include MDI main form ) and many dlls(mdi children form) , I wrote a form using CefSharp.winform as a Common.dll which are shared to many dlls.
i see that `https://github.com/cefsharp/CefSharp/issues/199` are closed. Do i need to use OffScreen package if i want to use it in winform Class Library? Otherwise, we must use it in .exe.

**Comment by amaitland** [comment]
You can use CefSharp in a class library and then reference that class library in a WinForms application.
