### ISSUE TITLE
chrome.runtime is not a function.....

### ISSUE THREAD

**Issue by addriumruss** [cefsharp/Questions-and-Support#13]
screen-sharing apps need chrome.runtime function. 
it seems not exist. 
anyone knows how to add this feature?

**Comment by amaitland** [comment]
As per https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=17042 this function is currently not implemented.

`CEF` has limited support for screen sharing to enable see https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=16952#p42886

You won't be able to use any extensions that reply on `chrome.runtime` until it's implemented, you can subscribe to https://bitbucket.org/chromiumembedded/cef/issues/1947/ for updates.
