### ISSUE TITLE
.NET Core EvaluateScriptAsync

### ISSUE THREAD

**Issue by zouql** [cefsharp/Questions-and-Support#19]
Win10x64、 .NET Core 3.1、CefSharp.WinForms 83.4.20

var browser = new ChromiumWebBrowser("https://github.com/cefsharp/CefSharp/issues");

var result = await browser.EvaluateScriptAsync("Promise.resolve(1)");

bug: result.Result == null;

**Comment by amaitland** [comment]
It's currently not possible to directly return a promise via EvaluateScriptAsync

We need support to be added in CEF first to handle this correctly, there is an open PR 
https://bitbucket.org/chromiumembedded/cef/pull-requests/291/improve-_cef_v8value_t/diff

You should be able to use DevTools to achieve this https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

You can directly execute DevTools commands see 
- https://github.com/cefsharp/CefSharp/issues/3158
- https://github.com/cefsharp/CefSharp/issues/3158#issuecomment-652705484
- http://cefsharp.github.io/api/83.4.x/html/M_CefSharp_DevToolsExtensions_ExecuteDevToolsMethodAsync_1.htm

**Comment by zouql** [comment]
Thanks.
