### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by zhizlm** [cefsharp/Questions-and-Support#2]
done

**Comment by amaitland** [comment]
@zhizlm Please don't delete the contents of your question. If you've resolved your question then post a comment and close the issue. 

The correct method of providing screen information is to override http://cefsharp.github.io/api/81.3.x/html/M_CefSharp_OffScreen_ChromiumWebBrowser_GetScreenInfo.htm

As the title and body are now meaningless this will likely be deleted.
