### ISSUE TITLE
Reset ExecuteScriptAsyncWhenPageLoaded with onetime flag set to false

### ISSUE THREAD

**Issue by luky92** [cefsharp/Questions-and-Support#20]
How do I reset loading script executed by ExecuteScriptAsyncWhenPageLoaded with one time flag set to false?

**Comment by amaitland** [comment]
What do you mean by `reset loading script`?

**Comment by luky92** [comment]
In my code I have something like this ExecuteScriptAsyncWhenPageLoaded("some js",false) and then it loads on every page reload and I was wondering if there is a way to stop that after some time for example let's say I have a script that I only need for specific website and then when I switch the website to another domain I want to stop that script from executing because it's no longer needed. I hope that makes sense

**Comment by amaitland** [comment]
ExecuteScriptAsyncWhenPageLoaded is an extension method and is built on the public API,  you can easily implement a more advanced version that meets your specific requirements. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp/WebBrowserExtensions.cs#L286

If you look at the source you can subscribe to the LoadingStateChanged event yourself and do some sort of dictionary lookup and load a different script based on the mainframe url.

http://cefsharp.github.io/api/83.4.x/html/M_CefSharp_WebBrowserExtensions_GetMainFrame.htm

**Comment by luky92** [comment]
You are right thanks for the tip
