### ISSUE TITLE
To Support “ShowDialogue ” method

### ISSUE THREAD

**Issue by UIViewController-1** [cefsharp/Questions-and-Support#21]
I’m Wants To Bind A JS Object To Save File,But When I Use`SaveFileDialogue1.ShowDialogue()`,The Compiler 
Shows That I’V To Use UI Thread

**Comment by amaitland** [comment]
What is your question exactly?

**Comment by UIViewController-1** [comment]
The Thread Apartment Is Not In `STAThread`,I Should Add STAThreadAttribute To `main()`,But There’s Already Have A`[STAThread]`in the `program.cs`

**Comment by amaitland** [comment]
All bound methods are called on the thread pool, to perform any sort of UI operation you must invoke onto the UI thread.

**Comment by UIViewController-1** [comment]
I Uses BackgroundWorker And Now it’s OK,Thank You
