### ISSUE TITLE
How Can I Hide CefShapp.BrowserSubprocess.exe From Task Manager?

### ISSUE THREAD

**Issue by Lebweuh** [cefsharp/Questions-and-Support#23]
Im running multiple (like 10) cefsharp processes and if you look task manager there are 10 CefShapp.BrowserSubprocess.exe
How can i hide it from TaskManager?

taskmanager image:
 ![here](https://user-images.githubusercontent.com/42931277/89441662-2bc96680-d756-11ea-89d3-35ce48c79261.PNG)
How can i hide it from task manager?

(if my english is bad, sorry)

**Comment by amaitland** [comment]
There's no way that I'm aware of. 

You can self host the browser sub process so your executable is used instead similar to how chrome launches multiple instances of Chrome.exe

**Comment by Lebweuh** [comment]
> There's no way that I'm aware of.
> 
> You can self host the browser sub process so your executable is used instead similar to how chrome launches multiple instances of Chrome.exe

yeah i understood. chrome does that. but how to do that?

**Comment by amaitland** [comment]
It depends on what features you use. If you use just the basic browser and nothing else then you can look at https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.WinForms.Example/Program.cs#L28 for an example. 

If you wish to self host the browser sub process that CefSharp provides then I upgraded the minimal example to demo this for .net core see https://github.com/cefsharp/CefSharp.MinimalExample/commit/898eb755c6bb7f504f9b5bdc889ff9142e105848 use https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.BrowserSubprocess.Core/WcfBrowserSubprocessExecutable.h instead for .net full.
