### ISSUE TITLE
Creating an App Package through a windows application packaging project fails to copy a dll

### ISSUE THREAD

**Issue by Snorvarg** [cefsharp/Questions-and-Support#25]
I am using CefSharp.Wpf 83.4.20 in a .net core 3.1 winform project. To clarify, I have tried using Cefsharp.WinForms as well, with the same result. Let's call the project StockCalc. I use Microsoft Visual Studio Community 2019, Version 16.6.4.

I install cefsharp as a nuget, select x64 as target, compile and it runs fine.

I create a windows application packaging project, and add a reference to StockCalc, compile.

It fails when I select Publish>Create App Packages, and try to build: The following warning pops up, and then follows an "Unspecified error occurred". 
Could not copy "C:\Users\xyz\.nuget\packages\cefsharp.common\83.4.20\CefSharp\x64\CefSharp.Core.dll" to "obj\x64\Release\PackageLayout\StockCalc\CefSharp.Core.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'obj\x64\Release\PackageLayout\StockCalc\CefSharp.Core.dll' because it is being used by another process. The file is locked by: "MSBuild.exe (13748)"	WapProj	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	3986	

..it seems the file CefSharp.Core.dll is locked by ..well MSBuild.exe. 

This happens even after restarting the computer, using different versions of cefsharp, installing a few updates of visual studio 2019. 

I also tried to reproduce the error with the MinimalExample ([CefSharp.MinimalExample](https://github.com/cefsharp/CefSharp)), it compiles fine. I created a windows application packaging project, and add a reference to the CefSharp.MinimalExample.WinForms.netcore project. 

I got exactly the same error here: 
Could not copy "C:\Users\xyz\.nuget\packages\cefsharp.common\83.4.20\CefSharp\x64\CefSharp.Core.dll" to "obj\x64\Release\PackageLayout\CefSharp.MinimalExample.WinForms.netcore\CefSharp.Core.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'obj\x64\Release\PackageLayout\CefSharp.MinimalExample.WinForms.netcore\CefSharp.Core.dll' because it is being used by another process.	WapProjTemplate1	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	3986	

The error messages I get are:
Error		PRI222: 0xdef00001 - Unspecified error occurred.	WapProjTemplate1	GENERATEPROJECTPRIFILE	1	
Error		PRI175: 0x8007000b - Processing Resources failed with error: An attempt was made to load a program with an incorrect format.	WapProjTemplate1	GENERATEPROJECTPRIFILE	1	

Also, when I try to Publish the minimalexample, I get these warnings:

Warning	NU1701	Package 'System.Windows.Interactivity.WPF 2.0.20525' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.	CefSharp.MinimalExample.Wpf.netcore	...\CefSharp.MinimalExample-master\CefSharp.MinimalExample-master\CefSharp.MinimalExample.Wpf\CefSharp.MinimalExample.Wpf.netcore.csproj	1	

and

Warning		The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`	WapProjTemplate1	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets	129	

I tried to give as much information as possible on this one, as IT HAS BEEN WORKING. I am afraid the error started to happen after some updates of visual studio, but I have no idea when it started to break.

Thank's for any help on this one.

**Comment by amaitland** [comment]
Maybe try on stackoverflow or reach put to Microsoft msbuild team as it was working? 

Sounds like a bug in msbuild.

**Comment by Snorvarg** [comment]
Alright, yeah I am lost on this one. 

I re-posted it here: 
https://stackoverflow.com/questions/63332539/creating-an-app-package-through-a-windows-application-packaging-project-fails-to

**Comment by amaitland** [comment]
Get you a wider audience,  I've not tried to publish a net core app. If I have anything to add then I'll continue the conversation on stackoverflow.
