### ISSUE TITLE
How do I get CefSharp to support.net framework 4.7.2

### ISSUE THREAD

**Issue by zaranetCore** [cefsharp/Questions-and-Support#26]
Hi , My project is wPF.NET framework 4.7.2, but unfortunately CefSharp.Wpf only stays at 4.5. What should I choose?

**Comment by amaitland** [comment]
.Net 4.5.2 is the minimum version required. When the documentation states 4.5.2 it's referencing the version used to compile the project. Anything newer is fine.

**Comment by zaranetCore** [comment]
Sorry to bother you. In my case, when I use Visual Studio to install through NUGET, it cannot be successfully installed, so I don't know how to operate.

**Comment by zaranetCore** [comment]
After nuget is installed, the reference list does not appear and cannot be found using.

**Comment by zaranetCore** [comment]
But in installed, it can be found

**Comment by amaitland** [comment]
Please confirm you've followed the post installation instructions. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/83/NuGet/Readme.txt#L8

**Comment by zaranetCore** [comment]
> 请确认您已按照安装后说明进行操作。
> 
> https://github.com/cefsharp/CefSharp/blob/cefsharp/83/NuGet/Readme.txt#L8

Thank you Very Much,Just solved the problem,Thank you again for
