### ISSUE TITLE
Intercept call post

### ISSUE THREAD

**Issue by totti240282** [cefsharp/Questions-and-Support#27]
- What version are you using? (exact version please e.g. 75.1.143, **not** Latest version as that's relative) Last version

- Are you using `WPF/WinForms/OffScreen`? WinForms

- Are you targeting .Net Core? If yes which version? .net Core and .net framework

Hello,
I would like to know if there is the possibility of intercepting GET / POST responses when I browse through the pages as it is done with the devtools.

**Comment by amaitland** [comment]
> * What version are you using? (exact version please e.g. 75.1.143, **not** Latest version as that's relative) Last version

Please specify the **exact version** you are using. Last version is not a valid version number.

> I would like to know if there is the possibility of intercepting GET / POST responses when I browse through the pages as it is done with the devtools.

Yes. Your two options are

- Implement [ResourceRequestHandler](http://cefsharp.github.io/api/83.4.x/html/T_CefSharp_Handler_ResourceRequestHandler.htm) see https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-interception for an example of how to plumb it in
- Use the `DevTools` protocol programmatically see https://github.com/cefsharp/CefSharp/issues/3158
