### ISSUE TITLE
How to solved this ?

### ISSUE THREAD

**Issue by mak27arr** [cefsharp/Questions-and-Support#30]
- What version are you using? (exact version please e.g. 75.1.143, **not** Latest version as that's relative)   79.1.360

- Are you using `WPF/WinForms/OffScreen`?    OffScreen

- Are you targeting .Net Core? If yes which version?        3.1

[0816/220130.491:INFO:CONSOLE(1)] "File chooser dialog can only be shown with a user activation.", source: about:blank (1)

**Comment by amaitland** [comment]
What exactly are you trying to achieve?
