### ISSUE TITLE
CefSharp donot support for webRTC? can‘t display video?

### ISSUE THREAD

**Issue by alwaysyangzhijin** [cefsharp/Questions-and-Support#31]
- What version are you using? (exact version please e.g. 75.1.143, **not** Latest version as that's relative)
### 75.1.141
- Are you using `WPF/WinForms/OffScreen`?
### WinForms
- Are you targeting .Net Core? If yes which version?
### no
- Can you reproduce the problem with the `MinimalExample`?

**Comment by amaitland** [comment]
That's a very old unsupported version. 

You must enable WebRTC. 

https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.cs#L47

**Comment by alwaysyangzhijin** [comment]
Already use  settings.CefCommandLineArgs.Add("enable-media-stream");

**Comment by amaitland** [comment]
Did you test with https://github.com/cefsharp/CefSharp.MinimalExample

If that doesn't work then you can ask on https://magpcss.org/ceforum/index.php

**Comment by alwaysyangzhijin** [comment]
yes, but it dosen't work

**Comment by amaitland** [comment]
Asked at https://magpcss.org/ceforum/viewtopic.php?f=6&t=17794
