### ISSUE TITLE
The CefSharp seems do not support WPF .net core version.

### ISSUE THREAD

**Issue by 18628271760** [cefsharp/Questions-and-Support#33]
- version : 84.3.10-pre

- WPF .net core version (core 3.1 and .net 5)

- Are you targeting .Net Core? yes. core 3.1 and .net 5

Hi team,
CefSharp  is a great product make web can display in WPF. But when I try to using .net core version, it throw an exception as: 
FileNotFoundException: Could not load file or assembly 'CefSharp.Wpf, Version=84.3.10.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. 

And my demo as follows:

<Window x:Class="WebInside.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WebInside"
        xmlns:cefSharp="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"   
        mc:Ignorable="d"
        Title="ChromeTest">
    <DockPanel LastChildFill="True">
        <Menu DockPanel.Dock="Top" VerticalAlignment="Top"/>
        <Viewbox Stretch="Fill">
            <Canvas HorizontalAlignment="Left" VerticalAlignment="Stretch" Width="1024" Height="630">
                <cefSharp:ChromiumWebBrowser x:Name="Web" Address="https://hlweb.jwell56.com/"/>
            </Canvas>
        </Viewbox>
        <StatusBar DockPanel.Dock="Bottom" Height="20" VerticalAlignment="Bottom"></StatusBar>
    </DockPanel>
</Window>

So, could u give me some idea about this? TKS!

**Comment by amaitland** [comment]
Did you read the Readme.txt file that opens when you install the Nuget package? 

https://github.com/cefsharp/CefSharp/blob/cefsharp/83/NuGet/Readme.txt#L17
