### ISSUE TITLE
two ChromiumWebBrowser communication, page loop refresh

### ISSUE THREAD

**Issue by fengtianjuedi** [cefsharp/Questions-and-Support#34]
cefsharp version: 84.4.10  branch: winform

**Comment by amaitland** [comment]
English only please. 

Please format your code, it's totally unreadable see https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by fengtianjuedi** [comment]
cefsharp version: 84.4.10 branch: winform

I have found the reason of this problem,this is duo to following code:
```c#
SplitScreenDisplayForm display = new SplitScreenDisplayForm();
display.Show();
this.Activate();
```
if my Main Form is ChromiumWebBrowser page, I'll open the sub ChromiumWebBrowser page again，and activate my main form. Will cause the program to flicker。the key is `this.Activate();`。
this problem does not exist in cefsharp 63。

Finally , Thank you for your reply

**Comment by amaitland** [comment]
The CEF behaviour has changed. 

See #2928 for background.
