### ISSUE TITLE
Hotkeys trigger  error

### ISSUE THREAD

**Issue by sunlei-ky** [cefsharp/Questions-and-Support#36]
F5 will be triggered  when i press T, and F11 will be triggered when i press Z.
Is there anything wrong with KeyboardHandler?
The version is 75.1.142

**Comment by amaitland** [comment]
> The version is 75.1.142

This version is old and unsupported.

**Comment by amaitland** [comment]
Version `84.4.10` is the current supported version, if the problem reproduces uses this version then please answer the questions listed at https://github.com/cefsharp/CefSharp/wiki/Questions-&-Support#when-asking-a-question-please-include-the-following
