### ISSUE TITLE
VB.net: inizialisize with iApp as null

### ISSUE THREAD

**Issue by tizu69** [cefsharp/Questions-and-Support#38]
`CefSharp.Cef.Initialize(settings, True, Null) 'Error here`
What can i do?

**Comment by amaitland** [comment]
Pass in null for browserProcessHandler

https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.cs#L59

**Comment by amaitland** [comment]
I've added an additional `Cef.Initialze(settings, performDependencyCheck)` to simplify this use case relevant commit https://github.com/cefsharp/CefSharp/commit/b0ee2f2bdaaebca472928cc10fccac5c014435d6

Changes will be included in the upcoming `85` release.
