### ISSUE TITLE
the method browser.Load(url)  can not navigator the url

### ISSUE THREAD

**Issue by wlnh420** [cefsharp/Questions-and-Support#39]
the code:

```
public class BaseResourceRequestHandler : ResourceRequestHandler
{
protected override void OnResourceLoadComplete(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, IResponse response, UrlRequestStatus status, long receivedContentLength)
        {
             browser.Load("http://www.xxx.com"); //but it is not navigator to http://www.xxx.com
    }

}
```

if i  use the code below   will be ok

public partial class FrmAddUser : Form{
      private void button1_Click(object sender, EventArgs e)
        {
            this.browser.Load("http://www.xxx.com");
        }
}

**Comment by amaitland** [comment]
Call Load directly on the frame. If calling http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_IFrame_LoadUrl.htm directly doesn't work you'll have to raise the issue upstream. 

IBrowser doesn't have a Load method from memory,  surprised if your code would even compile. 

Make sure you are testing with version 84.

**Comment by wlnh420** [comment]
> 
> 
> Call Load directly on the frame. If calling http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_IFrame_LoadUrl.htm directly doesn't work you'll have to raise the issue upstream.
> 
> IBrowser doesn't have a Load method from memory, surprised if your code would even compile.
> 
> Make sure you are testing with version 84.


i'm sure the vision 84.4.1. i exchange the method and use the code below instead but it dosn't to navigator http://www.xxx.com

```
public class BaseResourceRequestHandler : ResourceRequestHandler
{
protected override void OnResourceLoadComplete(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, IResponse response, UrlRequestStatus status, long receivedContentLength)
        {
             frame.LoadUrl("http://www.xxx.com"); //but it is not navigator to http://www.xxx.com too
    }

}
```

**Comment by amaitland** [comment]
I'm not sure if that's meant to work, best to ask on https://magpcss.org/ceforum/index.php as it's outside of our control.

**Comment by wnunezc** [comment]
this folder lines the stupid ... a folder where they put what they do not want to answer ...

**Comment by amaitland** [comment]
> this folder lines the stupid ... a folder where they put what they do not want to answer

@arcanisgk As stated above I don't know the answer and have provided a link for the appropriate place to ask. CefSharp is just one of many chromium embedded framework wrappers. There is a much larger community available at https://magpcss.org/ceforum/index.php

Please only comment if you have something constructive to add.

**Comment by wnunezc** [comment]
I'm not going to comment on anything else .. I'm going to sit down and see how stupid people waste their time publishing a query on how the hell this wrapper is installed ... with a minimum of code ...
