### ISSUE TITLE
JS-to-C# callback doesn't work

### ISSUE THREAD

**Issue by fandrei** [cefsharp/Questions-and-Support#40]
WinForms, 84.4.10

I'm trying to use a callback like this:
C#
```
	CefSharpSettings.LegacyJavascriptBindingEnabled = true;
	CefSharpSettings.WcfEnabled = true;
	_browser.JavascriptObjectRepository.Register("Callback", new CallbackFromJs(), false, BindingOptions.DefaultBinder);

// .......

	class CallbackFromJs
	{
		public void OnMessageClicked(string eventName, object eventData)
		{
			Debugger.Break();
		}
	}
```

JS
```
window.Callback.OnMessageClicked('Name', 'Data');
```

But getting this error message: `Uncaught TypeError: window.Callback.OnMessageClicked is not a function`
Any ideas what's wrong?

**Comment by amaitland** [comment]
> Method names are transformed to CamelCase (the first letter is transformed to lowercase, MyFunction becomes myFunction) by default. This is configurable by setting BindingOptions.CamelCaseJavascriptNames when you register your object, example below.

As per 
https://github.com/cefsharp/CefSharp/wiki/General-Usage#3-how-do-you-expose-a-net-class-to-javascript

> Type: CefSharp.BindingOptions
binding options, by default method/property names are camelCased, you can control this and other advanced options though this class.

http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_IJavascriptObjectRepository_Register.htm

For simple message passing I'd suggest using PostMessage see https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#JSEvent

If you'd like to improve the documentation anyone with a GitHub account can edit the wiki. PRs are also welcome. 

For reference the http://cefsharp.github.io/api/84.4.x/html/P_CefSharp_BindingOptions_CamelCaseJavascriptNames.htm property will be removed in the next major release see https://github.com/cefsharp/CefSharp/pull/3141

**Comment by fandrei** [comment]
@amaitland great, thanks.
