### ISSUE TITLE
Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by apurvshah** [cefsharp/Questions-and-Support#41]
- What version are you using? 81.3.100.0

- Are you using `WPF/WinForms/OffScreen`? WinForms.

- Are you targeting .Net Core? No

when add reference of CefSharp to the project and have "Generate Serialization assembly" setting as Auto/On, it gives error: SGEN : error : Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found. 

By turning that setting to off, this error will go away. But I need that setting to be on/auto as I will require that project.XMLSerializer.dll as part of the deployment. Is there any way to resolve this? Also, this error comes only in release mode. For Debug mode the project gets compiled successfully even the setting is set to Auto.

**Comment by amaitland** [comment]
Previous discussion on the topic at https://github.com/cefsharp/CefSharp/issues/2223#issuecomment-355150664

Closing as there is already an open issue.
