### ISSUE TITLE
Can't get ChromiumWebBrowser from popups

### ISSUE THREAD

**Issue by marcossapp** [cefsharp/Questions-and-Support#42]
Info:

- Version 84.4.10.0
- x64
- Win10
- WinForms

Problem:

I tried to open a popup as tab, following the code below based on WinForms.Example, which works fine. However I only can get the current ChromiumWebBrowser "loaded" for the parent page, for new popups as LifeSpanHandlers is not possible, so I can't figure out a way to open popup devtools for example.

**Comment by amaitland** [comment]
> I tried to open a popup as tab, following the code below based

You don't appear to have provided an example code.



> However I only can get the current ChromiumWebBrowser "loaded" for the parent page

What exactly is `loaded` in this context? It's really not very clear what your asking here.

> I can't figure out a way to open popup devtools for example.

Fundamentally each browser (popups included) is represented by an [IBrowser](http://cefsharp.github.io/api/84.4.x/html/T_CefSharp_IBrowser.htm) from which you can access all the fundamentals. `DevTools` is accessed via the [IBrowserHost](http://cefsharp.github.io/api/84.4.x/html/T_CefSharp_IBrowserHost.htm) where each `IBrowser` has a single `IBrowserHost`.

You can look at some of the extension methods in https://github.com/cefsharp/CefSharp/blob/cefsharp/84/CefSharp/WebBrowserExtensions.cs#L811 for some guidance.

You can take an `IBrowser` reference in http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_ILifeSpanHandler_OnAfterCreated.htm and free your reference when http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_ILifeSpanHandler_OnBeforeClose.htm is called

This is how `ChromiumWebBrowser` handles things internally for the main browser instance.

In future please don't ask questions in https://github.com/cefsharp/CefSharp, use one of the options listed at https://github.com/cefsharp/CefSharp#contact

**Comment by marcossapp** [comment]
@amaitland I gave up about posting the code because it was complicated to isolate the problem and forgot to remove the sentence. Sorry about that.

I read what you suggested and really helped me, thanks! I created a list of IBrowsers and added/removed them on ILifeSpanHandler methods you mentioned. so I just indexed by TabPage text property to get what IBrowser is related to the current tab. (Do you think it's bad?)

As you told about the procedure for question I am having a big issue about the SendMouseClickEvent on position absolute elements, so I will try to reproduce to post, may I create a new issue and and link the zipped project?

Thanks!

**Comment by amaitland** [comment]
> As you told about the procedure for question I am having a big issue about the SendMouseClickEvent on position absolute elements

- The WPF version uses sendmouseclickevent internally see https://github.com/cefsharp/CefSharp/blob/cefsharp/84/CefSharp.Wpf/ChromiumWebBrowser.cs#L2640 you can add some logging/debug statements to workout exactly what sequence is required. 
- Please make sure you do your research,  there are plenty of other SendMouseClickEvent questions https://stackoverflow.com/search?q=%5Bcefsharp%5D+SendMouseClickEvent

> link the zipped project

No zip files please,  I won't open them. If you need to provide an example then please fork https://github.com/cefsharp/CefSharp.MinimalExample squash your changes into a single commit and push your changes to GitHub. Keep them to the absolute minimum required to reproduce the problem.
