### ISSUE TITLE
CEF version conflict

### ISSUE THREAD

**Issue by VolodymyrMoldovan** [cefsharp/Questions-and-Support#43]
I am restricted to use CEF 3.3538.1849 version, because main process use this version.
There is no CEFSharp version for CEF 3.3538.1849.
When i am trying to use any version of CEFSharp i have an error.
"A procedure imported by 'CefSharp.Core.dll' could not be loaded"

**Comment by amaitland** [comment]
You'll have to use a different wrapper,  try CefGlue. 

https://gitlab.com/xiliumhq/chromiumembedded/cefglue

**Comment by amaitland** [comment]
https://stackoverflow.com/questions/63789264/cefsharp-version-in-matlab-2019b-runtime#comment112800615_63789264
