### ISSUE TITLE
close aplication via javascript.

### ISSUE THREAD

**Issue by wnunezc** [cefsharp/Questions-and-Support#44]
hello I have developed an application with CefSharp and C # .... to open a specific URL ...

I have an element in html "Log out" and I handle jquery "onClick" events to close the session.

How can I send to the  application from javascript a signal to close the entire application after the session has finished?

**Comment by amaitland** [comment]
In future please use on of the options listed at https://github.com/cefsharp/CefSharp#contact when asking a question. Please don't open a feature request to ask your question (I've transferred it to this repository).

---

Please answer the first few questions listed at https://github.com/cefsharp/Questions-and-Support/blob/master/.github/ISSUE_TEMPLATE/question-template.md
