### ISSUE TITLE
why use frame or webbrowser ,my auto login is good,use cefsharp can't not working

### ISSUE THREAD

**Issue by batsword** [cefsharp/Questions-and-Support#5]
x86 win10 net4.6.1.
cefsharp 71.0.1,
75.1.141,
79.1.360,
81.3.100
most can't auto login.

i was also setting 
settings.PersistSessionCookies = true;
settings.CachePath = Path.GetFullPath("cache\\global");

what happened?read cookie wrong?

I am embedding a wpf app using CefSharp which is all working fine. However, when logging into the app, CEF doesn't offer to remember the username and password like it does when opening the app in normal Chrome. cookie go wrong?

if i don't close app,then i  log out and it will be auto login.
if i close app,open app again,auto login went wrong

**Comment by amaitland** [comment]
Does your problem reproduce with the minimum example? 

https://github.com/cefsharp/CefSharp.MinimalExample

Check your log file for errors see https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#log-file

**Comment by batsword** [comment]
解决了
