### ISSUE TITLE
is screen-sharing supported in cef?

### ISSUE THREAD

**Issue by addriumruss** [cefsharp/Questions-and-Support#52]
is screen-sharing supported in cef?

**Comment by amaitland** [comment]
See https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=16952

**Comment by amaitland** [comment]
See also https://bitbucket.org/chromiumembedded/cef/issues/2993/webrtc-based-screen-sharing-capturing-not

**Comment by addriumruss** [comment]
Thanks so much, @amaitland! 
The above link seems to be a complicated solution for c++ cef to share screen, and we cannot select a specific screen.  Is there a way to select one specific screen and share it out in cefsharp?

**Comment by amaitland** [comment]
CefSharp is just one of many Chromium Embedded Framework(CEF) wrappers. Have a read of the first few paragraphs of https://github.com/cefsharp/CefSharp/wiki/General-Usage for a more detailed description. 

> The above link seems to be a complicated solution for c++ cef to share screen, and we cannot select a specific screen. Is there a way to select one specific screen and share it out in cefsharp?

CefSharp is built on top of CEF,  we are limited by what it supports. Short answer is no.

**Comment by addriumruss** [comment]
Thanks for support. 
Finally I compiled firefox to build screen-sharing application and it worked.
