### ISSUE TITLE
Could not able to push Cefsharp.WPF nuget package to private nuget gallary

### ISSUE THREAD

**Issue by SachinAmbokar** [cefsharp/Questions-and-Support#53]
Hi, I am trying to push Cefsharp.WPF nuget package to private nuget gallary. It error out with message : It
is a symbols package (it contains .pdb files and a /src folder). The server is configured to ignore symbols packages.).

**Comment by amaitland** [comment]
Please don't use the [Feature Request](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) template to ask questions.

You have already opened https://github.com/cefsharp/CefSharp/issues/3256 asking for a set of packages without symbols.

If you cannot reconfigure your `Nuget` repository then you'll have to build your own custom set of packages.

**Comment by SachinAmbokar** [comment]
Yes, I realize that its an issue rather than feature request.  But I was not able to modify it once it has been created. Apology for inconvenience.  However, I did not get completely from you comment to build my own custom set of packages. Could you please provide additional input on it.

Regards,
Sachin

**Comment by amaitland** [comment]
The https://github.com/cefsharp/CefSharp/blob/cefsharp/84/build.ps1 is used to compile the project and generate packages.  It defaults to compiling with VS2015, specify the Target parameters to use VS2017 or VS2019. The nuspec files live in the Nuget folder, you'll need to edit them. 

Reconfigured your Nuget repository is likely less effort.
