### ISSUE TITLE
According to the video tutorial on the official website, this exception appears after running

### ISSUE THREAD

**Issue by dzjfromChina** [cefsharp/Questions-and-Support#55]
According to the video tutorial on the official website, this exception appears after running
![1](https://user-images.githubusercontent.com/35582751/96454116-f9f07800-124d-11eb-9f61-4d57d43527e1.png)

vs studio version is 2019

**Comment by amaitland** [comment]
Please answer the questions listed at https://github.com/cefsharp/CefSharp/wiki/Questions-&-Support#when-asking-a-question-please-include-the-following

There are currently no official video tutorials,  and I'm not sure what you a referring to.
