### ISSUE TITLE
SendKeys.Send not working on On-Screen Keyboard

### ISSUE THREAD

**Issue by JaredDrakeZA** [cefsharp/Questions-and-Support#57]
Hello! I need your help ... 

I developed my very own On-Screen Keyboard component that is built-in with my own application, it has CEFSharp Web Browser in VB.NET app. 

NOTE: I am using touch-screen to run the app without keyboard and mouse. 

When loading my app with CEFSharp Web Browser, I used touch-screen to click on the username input and then clicked on a button via On-Screen Keyboard. It doesn't respond at all. Alternatively, I inserted the USB mouse and clicked on the username input and clicked on a button via On-Screen Keyboard, it just responded. 

Is it something like browser focus issue ? Or what ? 

Please help!

Many thanks!
Jared

**Comment by amaitland** [comment]
Issue transferred as questions should be asked in this repository please.
