### ISSUE TITLE
Is there a way to prevent CefSharp/CEF from sending server name during TLS client hello or is there a way to capture and modify it?

### ISSUE THREAD

**Issue by dylech30th** [cefsharp/Questions-and-Support#59]
I know this problem sounds weird but I do have this requirement for some special purpose, and I didn't found any way yet

**Comment by amaitland** [comment]
Already asked at https://stackoverflow.com/questions/64562078/is-there-a-way-to-prevent-cefsharp-cef-from-sending-server-name-during-tls-clien
