### ISSUE TITLE
Feature Request - My Feature

### ISSUE THREAD

**Issue by sxmny123** [cefsharp/Questions-and-Support#6]
How to modify the html content, is there any callback after the rendering is completed, or directly modify the html content method

**Comment by amaitland** [comment]
Please start by reading the following 
- https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-handling
- https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-interception
- https://github.com/cefsharp/CefSharp/wiki/General-Usage#response-filtering

What exactly are you trying to achieve?  Please give your issue a meaningful title.  In further please don't use a feature request to ask a question.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
