### ISSUE TITLE
Can't run this when select another compile output

### ISSUE THREAD

**Issue by lukasrmattos** [cefsharp/Questions-and-Support#62]
---
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
  Nuget 85.3.130

- **What architecture x86 or x64?**
    x86
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
    When I change my output compile:
![image](https://user-images.githubusercontent.com/28408973/98641684-ee531700-230a-11eb-8631-091e9ae4c758.png)

I Receive **System.BadImageFormatException.Assembly "CefSharp.Wpf**, but all files in wiki are there

If I change the output back to bin/debug its run fine. If I copy all content from bin/debug and put in any folder outside it (the exactly same files), I still receive this. I can just run it if inside debug folder. Any leads? I don't think it is any dll or file missing cause I'm copying it to test in my folder.

**Comment by amaitland** [comment]
What version of visual studio are you using?  Are you targeting. Net Core?

**Comment by lukasrmattos** [comment]
> What version of visual studio are you using? Are you targeting. Net Core?

2019, Net Framework 4.8.

So, I discovered that one of dlls inside my output when in same root folder of Cefsharp make cefsharp not to work. 

Any leads why cefsharp cant load itself when one of those dlls are in same folder?

http://www.mediafire.com/file/f98yvwe6c8gqf3g/DLLS.rar/file


I will run winmerge to get less candidates and I update here.

**Comment by lukasrmattos** [comment]
The dll dbghelp.dll in my folder made Cefsharp not work. I don't need this dll but for one reason it is on the game folder I'm using (game does not need this too).

I'm closing it but strange behavior

**Comment by amaitland** [comment]
Chromium uses dbghelp to create crash dumps as part of it's crashpad error handling. DbgHelp.dll ships with windows,  that is the version chromium will use by default. It is not a stated dependency as it is included in all supported versions of Windows. 

Possibly the version you have in your game folder is too old or is the incorrect bitness. Unfortunately .Net throws a misleading System.BadImageFormatException when it is unable to load a dll
