### ISSUE TITLE
.NET 5 WPF application file release cannot initialize CEF

### ISSUE THREAD

**Issue by HenJigg** [cefsharp/Questions-and-Support#63]
Try to synchronize the referenced dll and related files in the release folder, but it doesn't seem to work.

**Comment by amaitland** [comment]
Did you follow the .Net Core instructions?  https://github.com/cefsharp/CefSharp.MinimalExample#net-core-support

If you require further assistance then please answer the questions listed at https://github.com/cefsharp/CefSharp/wiki/Questions-&-Support#when-asking-a-question-please-include-the-following
