### ISSUE TITLE
HTML5 Video not displaying

### ISSUE THREAD

**Issue by lukaplayz** [cefsharp/Questions-and-Support#64]
Hello, so I am trying to play a html5 video hosted on my localhost in Minecraft specifically webdisplays. I put the correct URL and stuff and it loaded. But when I went over to play the HTML5 video, it was greyed out meaning I couldn't play the video?

Is there anyway I can fix it? It seems to be a bug.

**Comment by amaitland** [comment]
Only freely available audio and video codecs are supported. 

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo
