### ISSUE TITLE
is posible create a submenu??

### ISSUE THREAD

**Issue by wnunezc** [cefsharp/Questions-and-Support#65]
is posible create a submenu?

![image](https://user-images.githubusercontent.com/1207306/99721552-6d6bec00-2a7d-11eb-8f08-e2c60e497a0b.png)

**Comment by amaitland** [comment]
If you are referring to modifying the built-in context menu displayed when right clicking within the browser then yes.

You can customise the menu in [IContextMenuHandler.OnBeforeContextMenu](http://cefsharp.github.io/api/85.3.x/html/M_CefSharp_IContextMenuHandler_OnBeforeContextMenu.htm).

See https://github.com/cefsharp/CefSharp/blob/cefsharp/85/CefSharp.WinForms.Example/Handlers/MenuHandler.cs for an example of adding new menu items.

Specifically you can call [IMenuModel.AddSubMenu](http://cefsharp.github.io/api/85.3.x/html/M_CefSharp_IMenuModel_AddSubMenu.htm) to add a sub menu noting that it returns `IMenuModel` itself` for which you can then add menuitems to.
