### ISSUE TITLE
Could not load file or assembly 'CefSharp.Core, Version=85.3.130.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. 试图加载格式不正确的程序

### ISSUE THREAD

**Issue by alex-ling** [cefsharp/Questions-and-Support#67]
- What version are you using? (exact version please e.g. 75.1.143, **not** Latest version as that's relative)

- Are you using `WPF/WinForms/OffScreen`?

- Are you targeting .Net Core? If yes which version?

- No images of code/exceptions please, if you have a more than a few lines of code then please use [Gist](http://gist.github.com/), [Pastebin](https://pastebin.com/), [JsFiddle](https://jsfiddle.net/), [ControlC](https://controlc.com/) or similar. Post a link to example, 

- The [CefSharp.MinimalExample](https://github.com/cefsharp/CefSharp) is kept up to date with the latest version
  - You can use it for testing purposes
  - Take the project for a spin
  - Can you reproduce the problem with the `MinimalExample`?
    - Fork to provide a sample of your problem
    - Squash all your changes into a single commit
    - Only include nessicary changes to reproduce your problem, don't add code that's not relevant
    - Please don't remove the other examples that aren't relevant, just ignore then and keep your changes **Minimal**

**Comment by alex-ling** [comment]
ON Win-Server 2018

**Comment by amaitland** [comment]
English only please. Please make sure you've read https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

> ON Win-Server 2018

I've never heard of `Server 2018`.

There's insufficient information here to provide further support.
