### ISSUE TITLE
CefSharp.WinForms 81.3.100 sample application crashes

### ISSUE THREAD

**Issue by sanjaykulkarni04** [cefsharp/Questions-and-Support#7]
What version of the product are you using?
Nuget CefSharp.WinForms 81.3.100
What architecture x86 or x64?
 x64
On what operating system?
Win10
What is the .net framework?
4.5.2
Are you using WinForms, WPF or OffScreen?
WinForms
What steps will reproduce the problem?
Below is the sample code to reproduce issue
public partial class Form1 : Form
    {
        public ChromiumWebBrowser chromeBrowser;
        public Form1()
        {
            InitializeComponent();
            InitializeChromium();
        }
        public void InitializeChromium()
        {
            CefSettings settings = new CefSettings();
            // Initialize cef with the provided settings
            Cef.Initialize(settings);
            // Create a browser component
            chromeBrowser = new ChromiumWebBrowser("http://google.com");
            // Add it to the form and fill it to the form window.
            this.Controls.Add(chromeBrowser);
            chromeBrowser.Dock = DockStyle.Fill;   
        }        
        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            Cef.Shutdown();
        }      
    }
What is the expected output? What do you see instead?
Winforms not responding/crash and no errors are seen in the debug.log file. Even sometimes machine not responding and need to do a hard reboot. Sometimes CPU/Memory utilization shoots up to 100%.
Please provide any additional information below.
**_App.config file -_**
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<probing privatePath="x86"/>
		</assemblyBinding>
	</runtime>
</configuration>

I followed below steps for sample application test -

https://ourcodeworld.com/articles/read/173/how-to-use-cefsharp-chromium-embedded-framework-csharp-in-a-winforms-application

**Comment by sanjaykulkarni04** [comment]
I have all require .pdb files now. Where to find the detailed stack trace?

![image](https://user-images.githubusercontent.com/36174701/84271595-eb7cac00-ab49-11ea-8b31-bb48a6ffdffa.png)

**Comment by sanjaykulkarni04** [comment]
Alex, Can you please help to troubleshoot this issue?

Is it due to some securities policies applied in our network? How to verify that?

**Comment by amaitland** [comment]
Have you tested with the CEF Sample application? Please test as requested.

You haven't provided any details about your network so I cannot even speculate.

**Comment by amaitland** [comment]
The minimal example has crash reporting enabled as detailed in https://bitbucket.org/chromiumembedded/cef/wiki/CrashReporting.md#markdown-header-config-section

If "AppName" is set on Windows then crash report information (metrics, database and dumps) will be stored locally on disk under the "C:\Users\[CurrentUser]\AppData\Local\[AppName]\User Data" folder

See https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/crash_reporter.cfg#L11 for AppName.

You can load a dump in Visual studio or windbg to get a stack trace. The basics are at https://docs.microsoft.com/en-au/windows/win32/dxtecharts/crash-dump-analysis?redirectedfrom=MSDN#analyzing-a-minidump 

If you run the minimum example through visual studio make sure you enable native debugging and you should get a stack trace.

For windbg read
- https://www.chromium.org/developers/how-tos/debugging-on-windows/windbg-help has details on using windbg 
- https://stackoverflow.com/questions/10848585/how-to-read-a-google-chrome-crash-dump-with-windbg

Please test with the CEF Sample application as requested. This should be done before you analyze the crash dump.

**Comment by amaitland** [comment]
Transferring issue as this is a problem with your environment, not a bug.

Try disabling your antivirus temporarily. Contact your network admistrator and ask for help troubleshooting.

**Comment by sanjaykulkarni04** [comment]
Thank you Alex. I will check and let you know

Thanks
Sanjay

**Comment by sanjaykulkarni04** [comment]
Hi Alex,

Our network team still trying to figure out the root cause of this issue. 

However we created a new VM in same network and I tested **https://github.com/cefsharp/CefSharp.MinimalExample** sample application and it works great on VM. Even though our real production application works smoothly.

We verified few things like **anti virus/group policies/restrictions/permission/firewall settings** etc and compared them, they are same on my machine as well as on VM.

Now the question comes, why it is not working on my machine within same network?

Are they any hardware dependencies ? GPU configuration ? anything else?

Even logs doesn't help much.

Can you please help? 

Thanks
Sanjay

**Comment by sanjaykulkarni04** [comment]
Hi Alex,

I would really appreciate it if you could help me out, please.

Thanks,
Sanjay

**Comment by amaitland** [comment]
@sanjaykulkarni04 Please be patient, I am aware of your request and will respond when I have time to do so.

Try https://docs.microsoft.com/en-us/sysinternals/downloads/procmon to get a better understanding of the file system/registry calls that are being made.

**Comment by amaitland** [comment]
Please also make sure you've tested with the `CEF Sample Application` as I've previously requested.

**Comment by sanjaykulkarni04** [comment]
Hi Alex,

I downloaded CEF Sample Application from https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report and tested this application as per steps mentioned in this link. But no luck and I still have the same issue.

Below is the message from **debug.log** file -

[0619/222512.755:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 1 time(s)

![image](https://user-images.githubusercontent.com/36174701/85161234-18813b00-b27d-11ea-9de2-ccf28156cf07.png)

Thanks,
Sanjay

**Comment by sanjaykulkarni04** [comment]
I tried with disabling gpu option also -

cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled **--disable-gpu** --no-sandbox --disable-site-isolation-trials

**Comment by amaitland** [comment]
> But no luck and I still have the same issue.

That confirms the problem is totally unrelated to `CefSharp`. CEF has it's own support forum at https://magpcss.org/ceforum/index.php you can search through.

You can try the following to completely disable launching of the `GPU` process.

```
cefclient --disable-gpu --disable-software-rasterizer
```

You can test with a newer `cefclient` version from http://opensource.spotify.com/cefbuilds/index.html to see if an updated `Chromium` version helps.

Make sure you have Windows fully patched, graphics card drivers are up to date.

**Comment by sanjaykulkarni04** [comment]
> That confirms the problem is totally unrelated to `CefSharp`. CEF has it's own support forum at https://magpcss.org/ceforum/index.php you can search through.

I registered on the above portal, unfortunately, I am getting below error message while login, Even I tried option **Resend activation e-mail** couple of times but I did not receive an activation email.
Can you please activate my account?

![image](https://user-images.githubusercontent.com/36174701/85222061-4b8b1200-b3d6-11ea-989f-0b2ca1801338.png)

> You can try the following to completely disable launching of the `GPU` process.
> 
> ```
> cefclient --disable-gpu --disable-software-rasterizer
> ```
After trying the **cefclient --disable-gpu --disable-software-rasterizer** option, I am getting the below message (from **debug.log**) -

[0621/143914.321:WARNING:audio_output_device.cc(316)] Output device authorization timed out

> You can test with a newer `cefclient` version from http://opensource.spotify.com/cefbuilds/index.html to see if an updated `Chromium` version helps.

As you suggested, I tried with new version cef_binary_83.4.0+gfd6631b+chromium-83.0.4103.106_windows64_client. As usual, not working 👎 :-)

> Make sure you have Windows fully patched, graphics card drivers are up to date.

Meanwhile, I will check windows patches, audio, and graphics card, drivers, etc.

Thanks,
Sanjay

**Comment by sanjaykulkarni04** [comment]
Looks like the timeout error - **_Output device authorization timed out_** is coming from the below line no - 318

https://chromium.googlesource.com/chromium/src/media/+/master/audio/audio_output_device.cc

**Comment by amaitland** [comment]
Are other non-VM based computers within your company network working as expected? 
What version of Windows 10 are you using? Are you using a LTSC/LTSB build? 
What are the hardware specifications of your computer? 
What antivirus are you running? 


Please be detailed,  the more information the better.

**Comment by sanjaykulkarni04** [comment]
Hi Alex,

Please find the below details - 

> Are other non-VM based computers within your company network working as expected?

Yes, it's working in a few locations.

> What version of Windows 10 are you using? Are you using a LTSC/LTSB build?
> What are the hardware specifications of your computer?

![image](https://user-images.githubusercontent.com/36174701/85280334-9031ae80-b4a5-11ea-8228-7ca074db88db.png)

![image](https://user-images.githubusercontent.com/36174701/85281512-bf491f80-b4a7-11ea-9e54-20c539e28e04.png)

![image](https://user-images.githubusercontent.com/36174701/85281581-de47b180-b4a7-11ea-97a3-be136caa32db.png)

> What antivirus are you running?
Kaspersky Endpoint Security for Windows
 
Thanks
Sanjay

**Comment by amaitland** [comment]
Please answer the questions with replies to each one (No screenshot, too difficult to open on phone).

How does this compare to a computer that works as expected?

**Comment by amaitland** [comment]
You should now be able to register on ceforum. See https://bitbucket.org/chromiumembedded/cef/issues/2962/unable-to-register-in-your-forums

**Comment by sanjaykulkarni04** [comment]
Hi Alex,

Apologies for the delay in responding was tied up with other things. 

I worked with n/w team and did a comparison with my local machine hardware/anti-virus/restrictions/group policies/firewal/network/OS etc settings, mostly everything is identical.

I noticed, chrome GPU settings has lot of differences. Is this causing the issue? if yes how to fix? Can you please help me?

Thanks,
Sanjay

**Comment by amaitland** [comment]
Please confirm you have tested with the `CEF Sample Application` (cefclient)

**Comment by sanjaykulkarni04** [comment]
Yes Alex, already tested it.

http://opensource.spotify.com/cefbuilds/index.html

cef_binary_81.3.10+gb223419+chromium-81.0.4044.138_windows64_client.tar

**Comment by amaitland** [comment]
And?

**Comment by sanjaykulkarni04** [comment]
Hi Alex,

I am really happy to inform you that, the issue is resolved now. I really appreciate your precious assistance.

We are using **Forcepoint Endpoint** web protection security tool and it was in fall back mode. Once I re-installed the Forcepoint Endpoint client with the help info. sec. team, the CEF sample has started working fine. Even though our production-ready application is working smoothly now. I have noticed that JetBrains Toolbox and Spotify have **libcef.dll**  and was having a similar issue like the CEF sample application before fixing **Forcepoint Endpoint** client issue on my machine. Looks like **Forcepoint Endpoint**  was blocking web requests initially. It would have been really nice if the CEF sample application is able to log more info. about these kinds of issues.

I have a question, does the **libcef.dll** make web socket/request calls internally? Chrome and Microsoft chromium edge don't use **libcef.dll**?

Thanks,
Sanjay

**Comment by amaitland** [comment]
See https://bitbucket.org/chromiumembedded/cef/issues/2622/implement-support-for-networkservice

You can read all about CEF on it's project page https://bitbucket.org/chromiumembedded/cef/wiki/Architecture.md

**Comment by sanjaykulkarni04** [comment]
Sure, thank you so much, Alex
