### ISSUE TITLE
component refresh in app that implements cefsharp

### ISSUE THREAD

**Issue by wnunezc** [cefsharp/Questions-and-Support#70]
- What version are you using? 
85.3.13

- Are you using `WinForms and common`? yes with C#

**I have detected that after having the application that implements cefsharp minimized for some time or in the background,
bringing it back to the screen refreshes the URL and lost Session, someone can tell me:**
Why does it do that?
Is it normal for me to do so?
it can be avoided?
What can I do so that I do not lose the user session, if I am connected to a web with loggin? **(Important)**
What documentation is related to this behavior?  **(Important)**

**Comment by amaitland** [comment]
https://magpcss.org/ceforum/index.php would be a better place to ask. 

I've not seen this issue before and I don't remember any similar reports. As CefSharp is just one of many chromium embedded framework wrappers,  asking on the CEF support forum is the place to ask.

**Comment by wnunezc** [comment]
@amaitland  it is even more likely that they will return me to this place in search of an answer ... because they will say that if I am implementing this library it is the author who should look for the answer ... but hey. if nobody wants to support ... that bad.

**Comment by amaitland** [comment]
There is a CefSharp subforum at https://magpcss.org/ceforum/viewforum.php?f=18

Post a link back here and I will comment as required. 

CefSharp is just a wrapper, the browser itself is provided by CEF/Chromium.

**Comment by amaitland** [comment]
Asked at https://magpcss.org/ceforum/viewtopic.php?f=18&t=18024

Please continue the conversation there.
