### ISSUE TITLE
press Back button after Navigation is crashed app

### ISSUE THREAD

**Issue by bigfozzy** [cefsharp/Questions-and-Support#72]
1. Start WPF or WinForm Example
2. Go to google.com
3. Press Back button

Result: crashed and close a app 

System.AccessViolationException
  HResult=0x80004003
  Сообщение = Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by amaitland** [comment]
Issue has been transferred as bug report temple was not used. I have absolutely no idea what version you are using. 

Please review the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) and provide additional information.

**Comment by amaitland** [comment]
Closing as this is likely related to upstream issue  https://bitbucket.org/chromiumembedded/cef/issues/3052/cefclient-crash-reloading-when-you-use-the

Commit https://bitbucket.org/chromiumembedded/cef/commits/a717e440aadd suggests back, forward, reload and stop were fixed.

The master branch has been upgraded to a version which includes the reported fix. 
https://github.com/cefsharp/CefSharp/commit/a84d6e09589d9574f26c6dc1a6e755546e3e4be4

In future please use the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) when submitting an issue.
