### ISSUE TITLE
How to sing in google?

### ISSUE THREAD

**Issue by Interloperok** [cefsharp/Questions-and-Support#73]
Good afternoon, colleagues!

I am using CefSharp version 57 for my WPF project (.netFramwork 4.7.2). Unfortunately, I cannot change this, as the program, for which I develop my application, uses only this version.

I need to authorize on google, however, I see a message about an unsafe browser.

Can you please tell me what to do? Are there any solutions?

Thanks in advance for your answer!

**Comment by amaitland** [comment]
It is no longer possible see https://magpcss.org/ceforum/viewtopic.php?f=10&t=16764

**Comment by Interloperok** [comment]
Thanks for your answer!
