### ISSUE TITLE
Could not load file or assembly 'CefSharp.Core.DLL' or one of its dependencies

### ISSUE THREAD

**Issue by yvef** [cefsharp/Questions-and-Support#74]
- **What version of the product are you using?**
    - Any version from 73.1.12 up to 86.0.24 

- **What architecture x86 or x64?**
    x64
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    Create Microsoft Project Add-In.
   Open a browser after the add-in was started.

- **Please provide any additional information below.**
    - I have Add-In for MS Project. Even if I try to load the Cefsharp.core.dll assembly directly, I get such exception.
      In any other winforms projects that works fine. 

Do I know to clarify some point? 

Thanks.

**Comment by amaitland** [comment]
Does Microsoft project use Appdomains to load add-ins?

If so then it's unlikely you'll be able to get CefSharp running in the same process,  see https://stackoverflow.com/a/58077862/4583726 for background.

**Comment by yvef** [comment]
@amaitland Thank you for the info!

**Comment by amaitland** [comment]
If you can load the browser into the default appdomain then you can make it work.

Try checking https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.isdefaultappdomain?view=net-5.0

You can manually call Assembly.Load to pre-load CefSharp.Core.dll or use https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve?view=net-5.0 with Assembly.Load 

See https://github.com/cefsharp/CefSharp/issues/1714#issuecomment-227041722 for an example of AppDomain.CurrentDomain.AssemblyResolve
