### ISSUE TITLE
Set cookie in cefsharp

### ISSUE THREAD

**Issue by Masoud1721** [cefsharp/Questions-and-Support#76]
- What version are you using? (exact version please e.g. 75.1.143, **not** Latest version as that's relative)

- Are you using `WPF/WinForms/OffScreen`?

- Are you targeting .Net Core? If yes which version?

- No images of code/exceptions please, if you have a more than a few lines of code then please use [Gist](http://gist.github.com/), [Pastebin](https://pastebin.com/), [JsFiddle](https://jsfiddle.net/), [ControlC](https://controlc.com/) or similar. Post a link to example, 

- The [CefSharp.MinimalExample](https://github.com/cefsharp/CefSharp) is kept up to date with the latest version
  - You can use it for testing purposes
  - Take the project for a spin
  - Can you reproduce the problem with the `MinimalExample`?
    - Fork to provide a sample of your problem
    - Squash all your changes into a single commit
    - Only include nessicary changes to reproduce your problem, don't add code that's not relevant
    - Please don't remove the other examples that aren't relevant, just ignore then and keep your changes **Minimal**

**Comment by Masoud1721** [comment]
I am working with cefsharp in winform and need to add a cookie related to the login token cookies when initialize a cefsharp browser. How do I do this?
please help?

**Comment by amaitland** [comment]
In future please at least make an attempt to answer the questions listed in template.  

See https://github.com/cefsharp/CefSharp/blob/cefsharp/86/CefSharp.Example/Handlers/BrowserProcessHandler.cs for an example of calling SetCookie.

http://cefsharp.github.io/api/86.0.x/html/T_CefSharp_ICookieManager.htm

If you require further assistance then please provide more detail of what it is you are trying to achieve.

**Comment by Masoud1721** [comment]
hi ..
i use it..
thanks a lotttttttt 😊😊
