### ISSUE TITLE
CefSharp-cefsharp-79 builds 76.1.90.0

### ISSUE THREAD

**Issue by mikasta** [cefsharp/Questions-and-Support#8]
When i fetch the CefSharp-cefsharp-79 and build it in Visual Studio the resulting  dlls seems to be of version 76.1.90.0.

**Comment by amaitland** [comment]
> When i fetch the CefSharp-cefsharp-79 and build it in Visual Studio the resulting dlls seems to be of version 76.1.90.0.

Really this is safe to ignore

The build script updates the version numbers.

Run https://github.com/cefsharp/CefSharp/blob/cefsharp/79/build.ps1 to generate the set of `Nuget` packages. This will also update the assembly version info. 

For building with `vs2017` it would look like:
```
 .\build.ps1 -Target vs2017
```

Change the target to `vs2015` or `vs2017` or `vs2019` whichever suites you.
