### ISSUE TITLE
Capture the Point coordinates for a MouseDown event in cefSharp Winforms

### ISSUE THREAD

**Issue by kimkamp** [cefsharp/Questions-and-Support#9]
Hi. Trying to get the Point coordinates for a cefSharp Browser when I click on it.

I have navigation arrows on a website I am using, and I would like to be able to "push" a MouseClick in the browser. In order to do that, I need to first know the Point coordinates in the browser.

Looking for code to capture the Point coordinates, and looking for code to create a MouseClick event at the same Point coordinates.

Any help is appreciated - thanks!

Kim

**Comment by amaitland** [comment]
Your two options are using JavaScript or hooking the low level hwnd (not very user friendly). 

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#13-how-do-you-handle-a-javascript-event-in-c

https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L296

**Comment by kimkamp** [comment]
Thanks for the reply.

Using your first link, I was able to capture the MouseClick event in the Browser.

To get the Point location in the Browser, I used:

        Dim iMousePoint As Point = ChromiumWebBrowser.MousePosition
        If My.Computer.Keyboard.CtrlKeyDown = True Then
            Dim iMouseX As Integer = iMousePoint.X
            Dim iMouseY As Integer = iMousePoint.Y
            Dim iPoint As String = "X: " & iMouseX & ", Y: " & iMouseY
            txtURL.Text = iPoint
        End If

Next, I need to figure out how to push a MouseClick event in the Browser.

Any help you have would be appreciated. Also, any other resources/reference links would be appreciated

Thanks!

**Comment by amaitland** [comment]
> Next, I need to figure out how to push a MouseClick event in the Browser.

In my opinion it's not worth the trouble trying to trigger `Control.MouseClick` event. Just call a standard method that handles the mouse click behaviour.  

> Any help you have would be appreciated. Also, any other resources/reference links would be appreciated

You can parse the native `Win32` message and get the details you want, see https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-lbuttondown
